### ISSUE TITLE
세종대학교 구성원 인증 라이브러리 공유드립니다.

### ISSUE THREAD

**Issue by iml1111** [hanjo8813/SGH_for_AWS#74]
안녕하세요, 지난번에는 계정 정보 유출 제보해주셔서 정말 감사했습니다!

기존의 여러 교내 프로젝트에서 구성원 인증 기능이 자주 필요했던 것에서 시작하여 오픈소스 라이브러리를 개발하였습니다.

해당 모듈은 순수한 HTTP 통신만을 통해 인증 여부를 확인하기 때문에 selenium을 비롯한 자바스크립트 엔진을 탑재한 웹 드라이버에 비해 적은 리소스와 안정적인 결과를 가져올 수 있습니다. 

또한, 현재 기준 4가지의 인증 방법을 지원하기 때문에 학교측 서버 장애에서도 비교적 서비스 안정성을 확보할 수 있습니다. 잘부탁드립니다 :)

[sejong-univ-auth Repo 바로가기](https://github.com/iml1111/sejong-univ-auth)

**Comment by hanjo8813** [comment]
프로젝트 구성하신거 잘 봤습니다!
파이썬을 잘 몰라서 지금껏 드라이버 써가면서 인증했는데... 그냥 http로 요청보내는 방법이 있었군요... 
드라이버 쓰면서 오버헤드가 진짜 너무 커서 열받았는데 감명받았습니다 

게다가 라이브러리로 만들어주셔서 사용하기 정말 편해보였습니다. 당장 쓰고싶지만,,
 라이브러리에서 제공하는 정보에 PleaseGraduate의 인증방식에 필요한 정보가 들어있지 않아 현재로선 사용이 불가능할 것 같습니다 ㅜㅜㅜ

파이썬 고수신것 같아 제 [크롤링 코드](https://github.com/hanjo8813/PleaseGraduate/blob/master/app/views/crawler.py)를 보셔도 아시겠지만, 인증방식을 자세히 설명드리면

1. 대양휴머니티칼리지 로그인
    - ID/PW 틀릴시 예외처리
2. 나의 인증현황 페이지로 이동
   - **이동이 안되는 경우 존재 - 재외국민/편입생/계약학과 (가입불가) -> 예외처리**
3. 인증현황 페이지에서 학과명, 이름, 수료, **4가지 영역별 인증현황** 데이터를 긁어옴

<img width="721" alt="image" src="https://user-images.githubusercontent.com/71180414/167169216-eb468fc0-483f-4146-b6ef-82fc67136912.png">

위와 같은 흐름으로 동작하게 됩니다.
제공해주신 라이브러리 코드를 보니 비슷하게 동작하더라구요!
그래서 거의 모든걸 얻을 수 있었지만, PlaeseGraduate에서 사용하기 위해선 위의 과정에 bold 처리한 부분이 필요합니다. 

만약 위 기능을 추가해주실 의향이 있으시다면, 답변 남겨주셔서 얘기 나눠보고 싶어요!
감사합니다 😎

**Comment by iml1111** [comment]
오호 그런 문제가 있으셨군요. 한번 저도 알아보도록 하겠습니다!

2022년 5월 7일 (토) 오전 12:52, Jaewon Han ***@***.***>님이 작성:

**Comment by iml1111** [comment]
혹시 궁금한게 있습니다만, 올려주신 아래의 사진말인데요 아래가 아니라 위를 추출하고 싶으신게 아닌가요? 아니면 둘다 추출하고
싶으신건가요??
[image: image.png]

2022년 5월 7일 (토) 오전 1:44, HJ S ***@***.***>님이 작성:

**Comment by hanjo8813** [comment]
엇 혹시 메일로 보시고 계신가요? 
저는 이슈로 달아놔서 이슈 내용을 계속 수정했거든요 ㅜㅜ
수정된 이슈에서 사진은 하나라서 말씀드립니다

https://github.com/hanjo8813/PleaseGraduate/issues/74

**Comment by iml1111** [comment]
아아 그러셨던 거군요 .

제가 첨부한 이미지는 요거 입니다.
<img width="870" alt="image" src="https://user-images.githubusercontent.com/29897277/167238553-94e6533e-03aa-43c6-989f-46bc519c7a33.png">

제가 추측하기로는 현재 각 학생의 인증권수를 파악하시려고 하시는 것 같은데, 밑에 것이 아닌 위에것이 맞는게 아닌가? 싶어서요 ㅎㅎ

**Comment by hanjo8813** [comment]
아아..... 그렇네요 ㅋㅋㅋㅋㅋㅋㅋ 제가 동그라미를 잘못친걸 이해를 못했네요 ㅋㅋㅋㅋ
이수권수를 가져오는게 맞습니다!

**Comment by iml1111** [comment]
그렇군요 ㅎㅎ 마침 제가 지원하는 4가지 메소드중 하나인 ClassicSession 방식이 운좋게도 딱 저 페이지에서 정보를 추출합니다!

아마? 무리없이 추가 정보를 조회해드릴 수 있을 것 같아요. 테스트해본 뒤에 공유드릴게요!

**Comment by hanjo8813** [comment]
감사합니다~~ 
수정하시고 알려주시면 바로 적용해보겠습니다 ㅎㅎ (너무꿀이에요)

**Comment by iml1111** [comment]
적용후, Ver 0.3.2으로 pypi에 업로드해보았습니다!
```json
{
    "msg": "success",
    "result": {
        "authenticator": "ClassicSession",
        "body": {
            "grade": "3",
            "major": "컴퓨터공학과",
            "name": "신희재",
            "read_certification": {
                "과학 사상(1권)": "1 권",
                "동·서양의 문학(3권)": "3 권",
                "동양의역사와사상(2권)": "4 권",
                "서양의역사와사상(4권)": "4 권"
            },
            "status": "재학"
        },
        "code": "success",
        "is_auth": true,
        "status_code": 200,
        "success": true
    },
    "version": "0.3.2"
}
```

**Comment by hanjo8813** [comment]
오 감사합니다!! 
pip로 다운받아 테스트 해보고 라이브러리 깃허브 코드를 살펴봤는데, **나의 인증현황 페이지로 정상 이동이 안되는 경우** `ParseError`를 던지네용
이때 응답에서 아래와 같이 ID/PW를 틀렸을 경우와 동일한 메시지를 던져주는건가요?

```python
...
body={'message': '계정 정보가 잘못되었거나, 인증 포맷 자체에 문제가 있습니다.'}
...
```

제가 PleaseGraduate에서 크롤링할때의 예외 상황은 세가지로 나누어졌습니다.

1. ID/PW를 틀렸을 경우
2. 나의 인증현황 페이지로 정상 이동이 안되는 경우 -> 재외국민/편입생/계약학과 학생일 경우 발생
3. 알수없는 예외상황 (ex. 대휴칼 홈페이지 다운된 상황)

사용자들에게 정확한 오류 이유를 알려줘야하기 때문에, 이 세가지 예외상황이 응답메시지로 구분되어야 할 것 같습니다
(너무 귀찮게 하는것 같아 죄송하네요 ㅜㅜ)

**Comment by iml1111** [comment]
1번의 경우 정확하게 캐치할 수 있습니다만, 혹시 2번은 현재는 어떤 식으로 해당 조건을 판단하시는지 알 수 있을까요? 
인증 라이브러리로써 저도 2번 같은 경우는 반드시 탐지가 가능해야 할 것 같네요, 생각이 짧았습니다.

(혹시 추가적으로 다른 요구사항도 있으시면 부담없이 말씀해주세요!)

**Comment by hanjo8813** [comment]
저도 2번과 같은 경우를 처음에 모르고 코딩했다가 제보를 받았었는데...
지금 메일부터 쪽지까지 싹다 뒤져봤는데 어디갔는지.. 찾을수가 없네요 ㅜㅜ

<img width="809" alt="image" src="https://user-images.githubusercontent.com/71180414/167258869-36bc8c4e-a30b-4cd0-b190-8b93c59c0883.png">

아마 요거랑 비슷한 페이지가 떴던 걸로 기억해요
(즉 `나의 인증현황 페이지` html이 아니라 다른 html 페이지가 응답으로 올거에요)

**Comment by iml1111** [comment]
혹시 그럼 현재 어떤 코드에서는 해당 유저 아이디/비밀번호가 틀린게 아니라, 특수케이스라서 인증현황페이지로 가는 걸 식별하는 코드가 어딘지 짚어주실 수 있을까요? 그 부분 참고하면서 개발 진행해보겠습니다.

**Comment by hanjo8813** [comment]
```python
        # 고전독서 인증현황 페이지로 감, 실패시 재외국민/편입생/계약학과임
        try:
            driver.find_element_by_class_name("box02").click()  
        except:
            driver.quit()
            return 'err_enter_mybook'
```

<img width="923" alt="image" src="https://user-images.githubusercontent.com/71180414/167259131-76443d87-644a-4673-afcc-00d71692baf0.png">

이 부분입니다.
셀레니움을 쓰기때문에 저 박스를 클릭해서 인증현황 페이지로 이동합니다
근데 다시 코드를 보니까 특정조건 학생은 저기를 누르면 바로 오류가 떴었나 보네요...? 
1년전 일이라 자세히 기억이 안나네요 ㅜㅜ 제가 좀더 찾아볼게요

**Comment by iml1111** [comment]
아하... 정확한 태그 등으로 기준을 삼을 수 있다면 좋을 것 같은데 말이죠.

근데 의문인건 "편입생/재외국민이라서 못 들어간다" 이러한 구문도 아니고, 정말 저렇게 말도 안되는 페이지를 보여주면서 팅궈버리나요? 허허 참... ㅋㅋㅋ...

먼저 1, 3번의 경우 현재 바로 클리어가 가능할 것 같습니다.
2번의 경우, 현재 사용하고 있는 기준인 
- bs4 파싱 도중, None 탐지 (인증현황이 정상으로 호출된다면 당연히 있어야 할 태그들의 유무)를 통해 확인할 수는 있을 것 같습니다.

역시나 완전한 조건은 아니기 때문에 다른 Unknown Exception과 겹칠 수도 있긴 하겠네요...

**Comment by hanjo8813** [comment]
우선 2번은 이건 에타에 수소문해서 재외국민 입학자한테 도움을 받아볼게요 ㅋㅋㅋㅋ 
(맨날 이렇게 물어보고 만들었습니다...)

우선 말씀해주신대로 수정해주시면 바로 테스트 후 적용해보도록하겠습니다 ㅎㅎ

**Comment by iml1111** [comment]
추진력 리스펙합니다...  

https://github.com/iml1111/sejong-univ-auth/issues/13

위 링크는 말씀해주신 수정사항 반영중인 이슈 및 링크된 브랜치입니다. 여기서 지속적으로 코드 확인하시면서 테스트해주셔도 좋을것 같아요!

**Comment by hanjo8813** [comment]
2번 예외처리 관련해서 수소문해봤습니다.

원래는 재외국민 입학자도 대양휴머니티칼리지 사이트에 로그인 가능했고, 인증현황 페이지 이동시 팝업 뜨면서 아래 사진처럼 떴었다고 합니다

![image](https://user-images.githubusercontent.com/71180414/168126245-dfbc1204-0e98-484c-a6ca-0c15c0c814bd.png)

근데 지금은 대휴칼 정책이 바뀌었는지 재외국민 입학자가 아예 로그인이 안된다고 합니다. (대휴칼 사이트만)
학번/비번 틀렸을때랑 똑같은 창이 뜬다고 하네요 ;;

![image](https://user-images.githubusercontent.com/71180414/168127439-25d457d7-d2e9-4009-82cb-6e57759b65e6.png)

결론은... 그냥 현재 라이브러리 버전을 사용하면 될것 같습니다! (재외국민 입학자 예외 == 로그인 예외 ....)
결론이 났으니 낼 바로 적용해보겠슴다 ㅎㅎ

**Comment by iml1111** [comment]
오우 정말 수고하셨습니다! 그럼 제가 fix중인 부분이 있어서 그 부분 수정하여 버전 업데이트한후, 연락드리겠습니다. 오늘내로 빠르게
적용될테니 조금만 기다려주십시오!
2022년 5월 13일 (금) 오전 1:51, Jaewon Han ***@***.***>님이 작성:

**Comment by iml1111** [comment]
Ver 0.3.4 업데이트 완료했습니다 :)

**Comment by hanjo8813** [comment]
감사합니다~ 이제 작업해야겠네여

**Comment by hanjo8813** [comment]
적용완료했습니다!! 간만에 파이썬보니까 좀 어지러웠네요..ㅋㅋㅋ

라이브러리 적용해서 크롤링 방식 바꾸니까 시간이 최대 기준 10초 -> 2초로 줄었습니다. 
그리고 드라이버 때문에 도커 이미지 용량도 거의 3기가였는데 1기가로 줄었습니다.
~~대박이네요~~

개선할 생각을 안하고 있던 제가 부끄러워지네요..허허허
덕분에 서비스가 좀더 발전할 수 있었어요!  감사합니다~~!

---

아 추가적으로 궁금한게 있는데

<img width="245" alt="image" src="https://user-images.githubusercontent.com/71180414/168327227-553b97ba-2571-47dd-98e1-75d8a450fa79.png">

요기에 제 레포 추가되려면 어떻게 해야되나요? 저도 발자취를 남기고 싶어서...

**Comment by iml1111** [comment]
보통 python의 경우, requirement.txt에 작성이 되어있으면 자동으로 올라오는 걸로 알고 있거든요.
근데 Insight > Dependent Graph에 들어가보니 아래와 같이 떠있네요..

![image](https://user-images.githubusercontent.com/29897277/168412891-a9a0c615-f716-4224-a447-3470f9943c6d.png)

없는건 아닐테고 파일이 크다는 거 같은데.. 30라인도 크다고 할줄은 몰랐네요 ㅋㅋ...
보통 이러한 부분을 노출시키기 위해 아래와 같이 별도의 requirements.txt를 여러개 생성하기도 하시더라구요?!
![image](https://user-images.githubusercontent.com/29897277/168413103-db0e415e-9229-4dca-9d33-b9920c799945.png)

**Comment by hanjo8813** [comment]
알려주신 정보대로 무지성 시도해봤어요 ㅋㅋㅋㅋ

먼저 불필요 의존성 싹 지우고 커밋했는데... 계속 too large 떠서
알려주신대로 requirements.txt를 분리해봤는데 왠지 모르겠는데 계속 안되더라고요 ,,, (라이브러리 한 10개만 명시)
그래서 열받아서  requirements.txt에 `sejong-univ-auth` 라이브러리만 냅두고 커밋해봤는데도 안되네요... 후.....

github 공식문서 읽어봐도 제가 잘못한게 없는데 대체 왜그러는지 ㅜㅜㅜ 결국 실패하고 커밋 다 롤백 했슴다...........

---

라고 썼다가 공식문서에서 PR 어쩌구 써있길래 브랜치파고 PR로 머지했더니 추가되네요...? 하하하

<img width="674" alt="image" src="https://user-images.githubusercontent.com/71180414/168438494-c63e27aa-2a0a-4008-b844-fe904101134c.png">

발자취 남기기 성공했습니다 ㅎㅎ 고생하셨습니다~~
